(cl:in-package rosserial_arduino-msg)
(cl:export '(AB_DIR-VAL
          AB_DIR
          KK_DIR-VAL
          KK_DIR
          AB_VAL-VAL
          AB_VAL
          KK_VAL-VAL
          KK_VAL
          JOY1-VAL
          JOY1
          JOY2-VAL
          JOY2
          JOY3-VAL
          JOY3
          JOY4-VAL
          JOY4
          JOY5-VAL
          JOY5
          JOY6-VAL
          JOY6
          JOY7-VAL
          JOY7
          JOY8-VAL
          JOY8
          JOY9-VAL
          JOY9
          JOY10-VAL
          JOY10
))