(cl:in-package lowrabot-msg)
(cl:export '(MKN_DIR-VAL
          MKN_DIR
          MKR_DIR-VAL
          MKR_DIR
          MKN_VAL-VAL
          MKN_VAL
          MKR_VAL-VAL
          MKR_VAL
          JOY1-VAL
          JOY1
          JOY2-VAL
          JOY2
          JOY3-VAL
          JOY3
          JOY4-VAL
          JOY4
          JOY5-VAL
          JOY5
          JOY6-VAL
          JOY6
          JOY7-VAL
          JOY7
          JOY8-VAL
          JOY8
          JOY9-VAL
          JOY9
          JOY10-VAL
          JOY10
))